####################
#    BetterBees
# By AlonsoAliaga
####################

Messages:
  #Envoyé lors d'un clic droit sur une ruche ou un nid d'abeilles (sans l'objet en main).
  Hive-info:
    #Si "true" et "ProtocolLib" installé, le message sera envoyé dans la barre d'actions.
    #Sinon, il sera envoyé sous forme de message.
    Action-bar: true
    #Placeholders Disponible:
    # {HONEYLEVEL} - Niveau de miel dans la ruche.
    # {BEES} - Quantité d'abeilles.
    # {MAXHONEYLEVEL} - Toujours remplacé par 5.
    Message: "&e&lNiveau de miel: &b&l{HONEYLEVEL}/{MAXHONEYLEVEL} &f&l- &e&lAbeille: &b&l{BEES} &c❤"
  #Envoyé lors d'un clic droit sur une ruche ou un nid d'abeilles (avec l'objet en main).
  Hive-item-info:
    Action-bar: true
    Message: "&e&lNiveau de miel: &b&l{HONEYLEVEL}/{MAXHONEYLEVEL} &f&l- &e&lAbeille: &b&l{BEES} &c❤"
  Bee-info:
    Action-bar: true
    Message: "&e&lA du nectar: {NECTAR} &f&l- &e&lA une ruche: {HIVE} &f&l- &e&lA des fleurs: {FLOWER} &f&l- &e&lA une piqûre: {STING}"
  Keywords:
    Yes-word: "&a&lOui"
    No-word: "&c&lNon"
  Commands:
    #Vous pouvez utiliser des placeholders comme {VERSION} du {PLUGIN} pour afficher quelque chose comme:
    #No-permission: "&eRunning &6{PLUGIN} &ev&6{VERSION}&e."
    #Seulement dans "No-permission" message. Lorsque vous utilisez cela, vous soutenez le développeur :D
    No-permission: "&cVous n'êtes pas autorisé à exécuter cette commande."
    #exemple: "&f[{PLUGIN}] &cVous n'êtes pas autorisé à exécuter cette commande."
    Reloaded: "&aLa configuration a été rechargée."
    Help:
      - " &6&l&nBetterBees&e par AlonsoAliaga &7- &ev&6{VERSION}"
      - " &6/betterbees &f- &eAfficher ce message"
      - " &6/betterbees reload&f- &eRecharger les messages et quelques vérifications (n'inclut pas les hooks)"

Options:
  Permissions:
    #Permissions pour obtenir des informations. Si "none", il sera ignoré.
    Hive-info-permission: "none"
    Hive-item-info-permission: "none"
    Bee-info-permission: "none"
    #Permission d'accéder à /betterbees (qui inclut "/betterbees reload" qui recharge la configuration, mais seulement les messages sont mis à jour)
    Admin-permission: "betterbees.admin"
  Hooks:
    WorldGuard:
      #Hook WorldGuard si disponible. Si "false", rien concernant WorldGuard ne sera vérifié.
      #Désactivé par défaut. Aucune fonctionnalité pour le moment.
      Hook: false
    GriefPrevention:
      #Hook GriefPrevention si disponible. Si "false", rien concernant GriefPrevention ne sera vérifié.
      Hook: true
      #Empêchez les abeilles d'être endommagées sur les "claims", sauf pour les joueurs avec l'autorisations. Cela bloque TOUS les types de dommages.
      #inclus les EXPLOSION, INCENDIE, ETC! Seules les attaques des joueurs seront autorisées. Recommandé si vous utilisez des plugins avec des enchantements ou des effets personnalisés
      #Comme CrazyEnchantments ou similaire.
      #Cela NE DEVRAIT pas être nécessaire après que GriefPrevention ait mis à jour son plugin à 1.15
      #### (PLUS NÉCESSAIRE DEPUIS LA 1.15.1)
      Prevent-damage: true
      #Empêchez les joueurs de voler les ruches et les nids d'abeilles quand il n'a pas les autorisations.
      #Cela ne sera pas nécessaire après que GriefPrevention ait mis à jour son plugin en 1.15
      #Cela peut ne pas être nécessaire avec la dernière mise à jour de GriefPrevention. (PAS TESTÉ)
      #### (PLUS NÉCESSAIRE DEPUIS LA 1.15.1)
      Prevent-steal: false
    Lands:
      #Hook Lands si disponible. Si "false", rien concernant les lands ne sera vérifié.
      Hook: true
  Bees:
    Path-to-hive:
      #Si activé, il affichera une ligne entre l'abeille et l'emplacement de la ruche (si disponible).
      Enabled: true
      #Couleur des particules pour la ruche. La couleur doit être au format hexadécimal. N'incluez PAS le #
      #You can use this https://www.google.com/search?q=color+pick
      Color: "ebdc13"
      #Temps en secondes, le chemin de la ruche sera affiché. (Par défaut 2)
      Time: 2
    Path-to-flower:
      #Si activé, il affichera une ligne entre l'abeille et l'emplacement de la fleur (si disponible).
      Enabled: true
      #Couleur des particules pour les fleurs. La couleur doit être au format hexadécimal. N'incluez PAS le #
      #Vous pouvez utiliser ceci https://www.google.com/search?q=color+pick
      Color: "eb2113"
      #Temps en secondes, le chemin vers la fleur sera affiché. (Par défaut 2)
      Time: 2
  Lore:
    Enabled: true
    Message:
      - "&7Miel level: &6{HONEYLEVEL}&7/&65"
      - "&7Abeille: &6{BEES}"
      - ""
      - "&9Généré par BetterBees."
  #Que fait cette option?
  #Activer les noms automatiques pour les abeilless ;)
  Auto-name:
    Enabled: true
    Hooks:
      Global: true
      GriefPrevention: true
      Lands: true
    #Format utilisé si Global est activé.
    #Placeholders Disponible:
    # {BEENAME} - Remplacé par le nom aléatoire.
    Format-global: "&e{BEENAME}"
    #Format utilisé si l'abeille se reproduit dans une terre revendiquée (GriefPrevention ou Lands).
    # {BEENAME} - Remplacé par le nom aléatoire.
    Format-owner:
      #Placeholders Disponible:
      # {OWNER} - Remplacé par le nom du propriétaire du claim SI disponible (Uniquement avec GriefPrevention).
      GriefPrevention: "&e{BEENAME} &f- &6{OWNER}&e abeille"
      #Si Lands n'a pas de nom défini.
      Lands: "&e{BEENAME}"
      #Placeholders Disponible:
      # {LANDNAME} - Remplacé par le nom du terrain SI disponible (Uniquement avec Lands).
      Lands-name: "&e{BEENAME} &f- &6{LANDNAME}"
    #Liste de noms à choisir au hasard. (Vous pouvez également utiliser des couleur)
    Available-names:
      - "Jennie"
      - "Michael"
      - "Sunflower"
      - "Mike"
      - "Peter"
      - "Jane"
      - "Honey"
      - "Bumble"
      - "Pollen"
      - "Beeny"
      - "Taylor"
      - "Daisy"
      - "Alonso"
      - "Mary"
      - "Tony"
      - "&d&lQueen"
      - "PandaBarbe"

Updates:
  #ATTENTION: SI ACTIVÉ, LES COMMENTAIRES SERONT SUPPRIMÉS.
  Auto-update-configuration: false
  #Vérifier les mises à jour. (Recommandé de laisser cela activé!)
  Check-updates: true
  #Notifier les mises à jour lorsqu'un joueur rejoint le serveur.
  Notify-updates: true
  #Permission le joueur sera averti des nouvelles mises à jour lors de sa connexion au serveur.
  #Si "none" ou "nul", seuls les opérateurs seront notifiés.
  Permission: "betterbees.updatenotify"
  #Message envoyé lorsque la mise à jour est trouvée.
  Message: "&6[BetterBees] &eUne nouvelle mise à jour a été trouvée! Télécharge la ici &c{LINK}"
